import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { Sample } from "shared";

const Users: NextPage<{ data: unknown }> = (props: { data: unknown }) => {
  const { data } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Users List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sample />
        <h1 className={styles.title}>Users List</h1>

        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await axios.get(`https://dummyapi.io/data/v1/user?limit=10`, {
    headers: {
      "app-id": "62befb35a8d707e987d6f608",
    },
  });
  const data = res.data;

  // Pass data to the page via props
  return { props: { data } };
}

export default Users;
